taking data and libraries


In [65]:
import pandas as pd
import numpy as np
data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/supplement.csv")
data.head()

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0  T1000001         1         S1            L3          R1  2018-01-01   
1  T1000002       253         S4            L2          R1  2018-01-01   
2  T1000003       252         S3            L2          R1  2018-01-01   
3  T1000004       251         S2            L3          R1  2018-01-01   
4  T1000005       250         S2            L3          R4  2018-01-01   

   Holiday Discount  #Order     Sales  
0        1      Yes       9   7011.84  
1        1      Yes      60  51789.12  
2        1      Yes      42  36868.20  
3        1      Yes      23  19715.16  
4        1      Yes      62  45614.52

checking data

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             188340 non-null  object 
 1   Store_id       188340 non-null  int64  
 2   Store_Type     188340 non-null  object 
 3   Location_Type  188340 non-null  object 
 4   Region_Code    188340 non-null  object 
 5   Date           188340 non-null  object 
 6   Holiday        188340 non-null  int64  
 7   Discount       188340 non-null  object 
 8   #Order         188340 non-null  int64  
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB


In [67]:
data.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [68]:
data.describe()

Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

visualze data with piegraph

In [69]:
import plotly.express as px
pie = data["Store_Type"].value_counts()
store = pie.index
orders = pie.values

fig = px.pie(data, values=orders, names=store)
fig.show()

In [70]:

pie2 = data["Location_Type"].value_counts()
location = pie2.index
orders = pie2.values

fig = px.pie(data, values=orders, names=location)
fig.show()

In [71]:
pie3 = data["Discount"].value_counts()
discount = pie3.index
orders = pie3.values

fig = px.pie(data, values=orders, names=discount)
fig.show()

In [72]:
pie4 = data["Holiday"].value_counts()
holiday = pie4.index
orders = pie4.values

fig = px.pie(data, values=orders, names=holiday)
fig.show()

In [73]:

data["Discount"] = data["Discount"].map({"No": 0, "Yes": 1})
data["Store_Type"] = data["Store_Type"].map({"S1": 1, "S2": 2, "S3": 3, "S4": 4})
data["Location_Type"] = data["Location_Type"].map({"L1": 1, "L2": 2, "L3": 3, "L4": 4, "L5": 5})
data.dropna()


ID  Store_id  Store_Type  Location_Type Region_Code        Date  \
0       T1000001         1           1              3          R1  2018-01-01   
1       T1000002       253           4              2          R1  2018-01-01   
2       T1000003       252           3              2          R1  2018-01-01   
3       T1000004       251           2              3          R1  2018-01-01   
4       T1000005       250           2              3          R4  2018-01-01   
...          ...       ...         ...            ...         ...         ...   
188335  T1188336       149           2              3          R2  2019-05-31   
188336  T1188337       153           4              2          R1  2019-05-31   
188337  T1188338       154           1              3          R2  2019-05-31   
188338  T1188339       155           3              1          R2  2019-05-31   
188339  T1188340       152           2              1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [74]:
data.head()

ID  Store_id  Store_Type  Location_Type Region_Code        Date  \
0  T1000001         1           1              3          R1  2018-01-01   
1  T1000002       253           4              2          R1  2018-01-01   
2  T1000003       252           3              2          R1  2018-01-01   
3  T1000004       251           2              3          R1  2018-01-01   
4  T1000005       250           2              3          R4  2018-01-01   

   Holiday  Discount  #Order     Sales  
0        1         1       9   7011.84  
1        1         1      60  51789.12  
2        1         1      42  36868.20  
3        1         1      23  19715.16  
4        1         1      62  45614.52

In [75]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Region_Code"]=le.fit_transform(data["Region_Code"])

In [76]:
data["Region_Code"].head()

0    0
1    0
2    0
3    0
4    3
Name: Region_Code, dtype: int64

In [77]:
x=data.iloc[:,[1,2,3,4,6,7,8]].values
y=data.iloc[:,-1].values

In [78]:
x

array([[  1,   1,   3, ...,   1,   1,   9],
       [253,   4,   2, ...,   1,   1,  60],
       [252,   3,   2, ...,   1,   1,  42],
       ...,
       [154,   1,   3, ...,   1,   0,  56],
       [155,   3,   1, ...,   1,   1,  70],
       [152,   2,   1, ...,   1,   0,  47]])

In [79]:
y

array([ 7011.84, 51789.12, 36868.2 , ..., 31624.56, 49162.41, 37977.  ])

TRAIN MODEL by linear regression

In [80]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, 
                                                y, test_size=0.2, 
                                                random_state=42)

In [81]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [82]:
ypred = model.predict(xtest)
data = pd.DataFrame(data={"Predicted Orders": ypred.flatten()})
print(data.head())

   Predicted Orders
0      30610.379563
1      65378.006710
2      42593.518727
3      38368.197618
4      37622.022689


In [83]:
print(model.score(xtrain,ytrain)*100)
print(model.score(xtest,ytest)*100)

91.21312305554005
90.97527001788099


In [84]:
from sklearn.metrics import  r2_score
r2_score(ypred,ytest)

0.9020932431546211


by feature scaling 

In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(xtrain)

x_test = sc.transform(xtest)

In [86]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [87]:
x_train

array([[-1.07592873,  0.61022507],
       [ 1.12222243, -0.13270734],
       [ 1.89909961, -0.56146824],
       ...,
       [-1.05610093, -1.43199257],
       [-0.83376596,  0.78750518],
       [-0.83144368,  1.35494618]])

In [88]:
x_test

array([[-0.81216078,  2.21181639],
       [ 2.20811159,  0.85161734],
       [-0.66291027, -1.54772417],
       ...,
       [-1.73257615,  0.42010833],
       [-0.75151108, -0.69807488],
       [ 1.12594788, -0.6414334 ]])

In [89]:
from sklearn.linear_model import LinearRegression
model_1=LinearRegression()
model_1.fit(x_train,ytrain)

LinearRegression()

In [90]:
print(model_1.score(x_train,ytrain)*100)
print(model_1.score(x_test,ytest)*100)

71.51131830929862
71.10113342140916


In [91]:
y_pred = model_1.predict(x_test)
data_1 = pd.DataFrame(data={"Predicted Orders": y_pred.flatten()})
print(data.head())

   Predicted Orders
0      30610.379563
1      65378.006710
2      42593.518727
3      38368.197618
4      37622.022689


In [92]:
from sklearn.metrics import  r2_score
r2_score(y_pred,ytest)

0.5990954509139523

doing it by lightgbm

In [93]:
import lightgbm as ltb
model = ltb.LGBMRegressor()
model.fit(xtrain, ytrain)

LGBMRegressor()

In [94]:
ypred_lgbm = model.predict(xtest)
data = pd.DataFrame(data={"Predicted Orders": ypred_lgbm.flatten()})
print(data.head())

   Predicted Orders
0      28624.830156
1      67286.086174
2      40361.278413
3      36698.241579
4      36386.815996


In [95]:
from sklearn.metrics import  r2_score
r2_score(ypred_lgbm,ytest)

0.9425299922897604